[PROF-2585] Warn on incompatible rollbar version
DataDog/dd-trace-rb pull request #1300
Opened 2021-01-06 12:34 UTC by ivoanjo

Rollbar gem versions <= 3.1.1 have an incompatibility with ddtrace's
CPU profiling. This was ack'd and fixed upstream in
<https://github.com/rollbar/rollbar-gem/pull/1018>.

This commit adds code to detect when customers are still using a legacy
version of rollbar, printing a warning to ask them to upgrade.

Note: Because the fixed version of rollbar has not yet been released,
the tests that validate that the warning is not shown on unpatched
versions are disabled and tagged with a FIXME.

See the "FIXME NEW ROLLBAR NEEDED" note in the setup_spec.rb for more
details on what's disabled and what steps we need to take once the
new version gets released.

First commit @ Datadog 🎉

2021-01-07 15:09 UTC, ericmustin approved these changes
not super familiar with the profiling branch yet but generally lgtm, deferring to @delner here though

2021-01-07 20:27 UTC, delner requested changes
I think the actual warning itself looks good! However, I think we could leverage a test helper to greatly simplify the tests for this, and eliminate much of the appraisal related changes.

We did this in another file, which tested for behavior based on the presence or non-presence of a gem (and its version):

```ruby
RSpec.describe Datadog::Contrib::Faraday::Integration do
  extend ConfigurationHelpers

  describe '.version' do
    subject(:version) { described_class.version }

    context 'when the "faraday" gem is loaded' do
      include_context 'loaded gems', faraday: described_class::MINIMUM_VERSION
      it { is_expected.to be_a_kind_of(Gem::Version) }
    end

    context 'when "faraday" gem is not loaded' do
      include_context 'loaded gems', faraday: nil
      it { is_expected.to be nil }
    end
  end
  ```
  
  I think you could use this, and remove all the appraisal changes. What do you think @ivoanjo ?

2021-01-08 09:00 UTC, ivoanjo commented
Ah, interesting. It took me a few minutes to wrap my head around what the helper was doing ;)

If I understand correctly, the `loaded gems` helper simulates looking up the info on a gem that is loaded (e.g. the response from `Gem.loaded_specs`).

I think the general idea would work for this PR. The tests in my first attempt are more realistic, but they do introduce a number of extra steps (and make testing slower), as well as making it hard for testing all variants in one run (you always need to restart your ruby with different environments).

I can't quite use the helper directly since I'm using `Gem::Specification.find_all_by_name` which differs from `Gem.loaded_specs` because it includes gems that may not be loaded:

```ruby
$ pry
[1] pry(main)> Gem.loaded_specs.keys.include?("rollbar")
=> false
[2] pry(main)> Gem::Specification.find_all_by_name("rollbar").map { |it| [it.name, it.version] }
=> [["rollbar", Gem::Version.new("3.1.1")], ["rollbar", Gem::Version.new("2.27.1")]]
```

...but the approach is the same -- I shall mock the other method instead.

Now I shall quote Arnie:

![](https://media.giphy.com/media/rOsebqhlfCRby/giphy.gif)

2021-01-08 21:57 UTC, delner approved these changes
I think the use of mocks here is appropriate (`Gem::Specification` is a stable API) and serves us well in simplifying the test code; it's now much easier to reason about its mechanisms.

Nice work @ivoanjo ! Thank you :)

2021-01-11 08:55 UTC, merged