[ci-app] Add User Provided Git Metadata
DataDog/dd-trace-rb pull request #1662
Opened 2021-08-27 08:16 UTC by juan-fernandez

## Motivation
Provide a way for users to provide `git` metadata when other methods fail. 

## How
* Read certain environment variables and set them as span tags if they're present. These take precedence over other methods to get `git` metadata. 

**Note**: I don't understand what's happening with `sorbet`'s job. If I run the typecheck in master the same errors show, so I'm not sure if they're related to my changes. Also, the files with errors seem not to be the ones I changed?

2021-08-30 14:07 UTC, delner requested changes
Overall seems fine, but I think we should migrate some constants to follow convention.

2021-08-30 14:07 UTC, delner commented on lib/datadog/ci/ext/environment.rb
> +          }.reject { |_, v| v.nil? || v.empty? }
I would recommend using `strip` on the values first, as sometimes users will introduce whitespace characters that will make the string "not empty", e.g.:

```
2.5.1 :002 > ' '.empty?
 => false
 ```

2021-08-30 14:07 UTC, delner commented on lib/datadog/ci/ext/environment.rb
> +            Datadog::Ext::Git::TAG_REPOSITORY_URL => env['DD_GIT_REPOSITORY_URL'],
All these strings should be frozen, migrated to `Datadog::Ext::Git` and prefixed with `ENV_`

e.g. `'DD_GIT_REPOSITORY_URL'` => `Datadog::Ext::Git::ENV_REPOSITORY_URL = 'DD_GIT_REPOSITORY_URL'.freeze`

2021-08-30 14:07 UTC, delner commented on spec/datadog/ci/ext/environment_spec.rb
> +              'git.branch' => 'my-branch',
Minor suggestion, but you could derive these values from the `env` above e.g. `'git.branch' => env['DD_GIT_BRANCH']`

2021-09-08 19:07 UTC, marcotc approved these changes

2021-09-08 19:07 UTC, merged