Better naming for Tracer#call_context argument
DataDog/dd-trace-rb pull request #1692
Opened 2021-09-17 21:47 UTC by marcotc

In `Datadog::Tracer`, this PR renames the argument
```ruby
def call_context(key = nil)
```
to 
```ruby
def call_context(thread = nil)
```
to clarify that we are extracting the call context from a thread.

By default, the current thread's context is retrieved, which is now documented in RDoc.

I made a small change to ContextProvider to clean up the handling of the default value, for when a `thread` is not provided, but there are not functional changes from this modification.

2021-09-20 08:32 UTC, ivoanjo approved these changes
Left two small notes, otherwise LGTM, thanks for making this clearer 👍

2021-09-20 08:32 UTC, ivoanjo commented on lib/ddtrace/tracer.rb
> +    def call_context(thread = nil)
Minor: "Defaults to current thread" is semantically true, but I guess somewhat confusing seeing as the next line says `thread = nil` . Perhaps this should be

> [Thread] the thread to retrieve the context from. `nil` means current thread. Defaults to `nil`.

...or something similar?

2021-09-20 08:32 UTC, ivoanjo commented on spec/ddtrace/context_provider_spec.rb
> -
I believe this removal [breaks the subject](https://app.circleci.com/pipelines/github/DataDog/dd-trace-rb/4305/workflows/dea6b510-15a4-45be-b308-7d6c6d214660/jobs/164101)

2021-09-20 19:49 UTC, delner requested changes
I think this change marries us to a specific use of the `ThreadLocalContextProvider`, whereas the point of `call_context` was an abstraction that could resolve a `Context` from other sources (including distributed ones.)

If this is necessary for some immediate, practical purpose, I'd like to hear more about that. But otherwise there is plan to tackle/change context management soon anyways.

2021-09-28 22:06 UTC, marcotc commented
This PR only exists because `key` in `def call_context(key = nil)` is misleading: `key` here actually has to be a context carrier that responds to `[]`.

I think I named it `key` back when the `@key` that you now see in `thread[@key] ||= Datadog::Context.new` was actually provided through the API, but this has since changed without an accompanying name change.

A better name would be something along the lines of `context_carrier` or `context_provider`, but none sound that good to me.

2021-10-04 20:44 UTC, marcotc commented
I'm closing this for now, as this part of our code base won't stay in the same shape in the future.

2021-10-04 20:44 UTC, closed without merging