Avoid setting `:exception` on payload object, as it's never used
DataDog/dd-trace-rb pull request #1751
Opened 2021-11-02 10:55 UTC by ivoanjo

At some point in the past, this seems to have been used, but we no longer reference it anywhere, and instead use `:exception_object` to get the information directly.

2021-11-02 21:29 UTC, delner requested changes
I don't think this is quite right.

Although in the case of `ActionController` we are setting this value in the payload and not using it, we employ the same technique in other instrumentation, most notably `ActionView` and `ActiveSupport`, in which it is used. At the very least, we have an issue with consistency that needs to be addressed (even if that ultimately means we drop `:exception` everywhere.)

This `Array` value matches what we have defined in `error.rb`, and is legal input. So my sense is that this strategy might be important to making sure errors show up on our instrumentation properly. Maybe `ActionController` should have been using this `payload[:exception]` to `set_error`, or maybe it should be using `:exception_object` to set the error instead, if that's possible.

I would like to determine the right strategy that 1) preserves the error tag feature, and 2) is consistently applicable across these integrations, and 3) addresses any performance issues that may need to be addressed (which is my understanding of why we want to make this change.)

In any case, points outstanding to me are:

 - Where/how should `ActionController` be setting the error here?
 - Why is it expensive to access `e.message`? Is there a better way to ensure this value is appropriately tagged on the active span?

2021-11-03 09:20 UTC, ivoanjo commented
I see this as a quick cleanup of something that isn't needed in this particular case; it's definitely not a fix for any problematic exceptions.

I... hadn't planned on making this a larger investigation/refactoring. If we think we don't want this quick cleanup by itself, my suggestion is to close off the PR, as I don't currently have the bandwidth to go after the larger investigation.

2021-11-03 18:07 UTC, marcotc commented on lib/ddtrace/contrib/action_pack/action_controller/instrumentation.rb
>                  raise e
Looks like we were trying to emulate ActiveSupport::Notifications internals: https://github.com/rails/rails/blob/93b7bd5ce23a96548bf93667e416037dee40d90d/activesupport/lib/active_support/notifications/instrumenter.rb#L25-L28

But the `payload` object is only used by us, never returned to the Rails framework.

2021-11-03 18:11 UTC, marcotc approved these changes
This seems like a field we added to keep our error information in a [similar shape to Rails' own error information](https://github.com/rails/rails/blob/93b7bd5ce23a96548bf93667e416037dee40d90d/activesupport/lib/active_support/notifications/instrumenter.rb#L25-L28), but it was never used by us, [not even in the original PR that introduced it](https://github.com/DataDog/dd-trace-rb/pull/795/files#diff-c7c7564cc5bbf99b570001291ddb26f2f03c6804a3727a0a721a8da8658eaeefR120).

2021-11-03 18:45 UTC, delner commented
@marcotc That PR didn't introduce it, it merely migrated it. It used to exist in this file. History beyond that I don't know off the top of my head. https://github.com/DataDog/dd-trace-rb/pull/795/files#diff-ade263dd4c26c0cd26b8f7956fa5673d5966cd2397d5918a08a30b0eb3b1abf1L55

Still interesting that it actually exists within Rails itself, and you're probably right that it was added to mirror Rails. Just want to ascertain what the vision is here for Rails instrumentation and error tagging before we remove this. Should it always & only tag `:exception_object`? Or should it be doing something else?

2021-11-05 23:18 UTC, marcotc commented
@delner, the `payload` hash in question is only used in the local method scope of `#process_action`: https://github.com/DataDog/dd-trace-rb/blob/e391d2eb64d3c6151a4bdd2710c6a8c7c1d57457/lib/ddtrace/contrib/action_pack/action_controller/instrumentation.rb#L106-L140

In this context, `payload` holds state and is passed around to  [three](https://github.com/DataDog/dd-trace-rb/blob/e391d2eb64d3c6151a4bdd2710c6a8c7c1d57457/lib/ddtrace/contrib/action_pack/action_controller/instrumentation.rb#L76) [different](https://github.com/DataDog/dd-trace-rb/blob/e391d2eb64d3c6151a4bdd2710c6a8c7c1d57457/lib/ddtrace/contrib/action_pack/action_controller/instrumentation.rb#L17) [methods](https://github.com/DataDog/dd-trace-rb/blob/e391d2eb64d3c6151a4bdd2710c6a8c7c1d57457/lib/ddtrace/contrib/action_pack/action_controller/instrumentation.rb#L38) in order for them to operation on the information contained in `payload`. In that sense, we are using procedural programming, instead of object-oriented, in this method: we captured the state in a object and pass it around methods, instead of having a class that encapsulates both state and methods.

With this, `payload` is effectively private to `Datadog::Contrib::ActionPack::ActionController::Instrumentation`, and it is a short lived object that never gets passed to any methods outside of `Datadog::Contrib::ActionPack::ActionController::Instrumentation`.

2021-11-08 10:18 UTC, ivoanjo commented
> With this, payload is effectively private to Datadog::Contrib::ActionPack::ActionController::Instrumentation, and it is a short lived object that never gets passed to any methods outside of Datadog::Contrib::ActionPack::ActionController::Instrumentation.

Thanks Marco for the great description. This was exactly how I read it, and why I decided to do the cleanup.

2021-11-10 21:49 UTC, marcotc reviewed
Could you also clean up  https://github.com/DataDog/dd-trace-rb/blob/9e75a243be861d5963e4b0c55b4223b607bae30e/lib/ddtrace/contrib/active_support/cache/instrumentation.rb#L107-L108?
It looks like it has the same behaviour of storing duplicate keys for internal usage.

2021-11-11 10:27 UTC, ivoanjo commented
> Could you also clean up ...? It looks like it has the same behaviour of storing duplicate keys for internal usage.

Actually that one is kinda interesting because it has the reverse behavior of the one I submitted -- it sets both `:exception` and `:exception_object` BUT actually only uses the `:exception`, not the `:exception_object` (and thus, if I'm following it right, it never captures stack traces for errors on these spans):

https://github.com/DataDog/dd-trace-rb/blob/9e75a243be861d5963e4b0c55b4223b607bae30e/lib/ddtrace/contrib/active_support/cache/instrumentation.rb#L59

Just to avoid rework: do you think it makes sense to change the activesupport cache instrumentation to use the `:exception_object` instead, and then clean up the `:exception`?

2024-07-30 15:14 UTC, ivoanjo commented
I suspect this optimization is still applicable, but I'll close this one for now to clean up our list of old PRs.

2024-07-30 15:14 UTC, closed without merging