Added WAF vendors headers in traces tags
DataDog/dd-trace-rb pull request #3528
Opened 2024-03-15 12:29 UTC by vpellan

**What does this PR do?**
Add WAF vendors headers in traces tags according to this [RFC](https://docs.google.com/document/d/1xf-s6PtSr6heZxmO_QLUtcFzY_X_rT94lRXNq6-Ghws)

**Motivation:**
This will enable the ASM Respond team to parse the value of these headers and check that they are in the correct format

**Additional Notes:**
I used a hash to access traces-formatted headers and rack-formatted headers at the same time, and this hash is created from a list of string, corresponding to the HTTP-formatted header. Maybe these operations can add overhead time, and manually creating the hash would be faster

**How to test the change?**

1. Use Rspec (`-e 'with WAF vendors headers'`)
2. Use [system-tests](https://github.com/DataDog/system-tests)
	- Enable Test_ExternalWafRequestsIdentification in ruby manifest
	- `run.sh tests/appsec/test_traces.py::Test_ExternalWafRequestsIdentification::test_external_wafs_header_collection`
	- Check on datad0g staging that the trace contains WAF headers tags

**For Datadog employees:**
- [ ] If this PR touches code that signs or publishes builds or packages, or handles
credentials of any kind, I've requested a review from `@DataDog/security-design-and-guidance`.
- [x] This PR doesn't touch any of that.

2024-03-20 10:40 UTC, lloeki approved these changes
LGTM, save for a minor suggestion

2024-03-20 10:40 UTC, lloeki commented on lib/datadog/appsec/contrib/rack/request_middleware.rb
> +            add_http_headers_tags(scope, env)
See below

```suggestion
            add_request_tags(scope, env)
```

2024-03-20 11:01 UTC, ivoanjo requested changes
Note: Please hold off on merging this to master until we get the 1.21.1 release out. (Feel free to dismiss afterwards! Thanks for the patience!)

2024-03-25 15:41 UTC, lloeki approved these changes
LGTM, just an extra comment left

2024-03-25 15:41 UTC, lloeki commented on lib/datadog/appsec/contrib/rack/request_middleware.rb
> +        # .map { |s| [s.downcase, Datadog::Tracing::Contrib::Rack::Header.to_rack_header(s)] }.to_h
Leftover comment, to be removed ;)

2024-03-25 16:17 UTC, ivoanjo commented on lib/datadog/appsec/contrib/rack/request_middleware.rb
> +        # Create an array of lowercased headers
Minor: I don't think this comment adds a lot, reminds me of this meme lol :wink: :wink: :wink: :wink::

![](https://res.cloudinary.com/practicaldev/image/fetch/s--aIBPDZ9g--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_800/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/fal0udi31n6r3pwg8d73.png)

2024-03-25 16:33 UTC, merged