Build oci package
DataDog/dd-trace-rb pull request #3662
Opened 2024-05-23 14:18 UTC by randomanderson

**What does this PR do?**
Builds and publishes the OCI package for ruby

**Motivation:**
OCI packages are needed for the datadog install and fleet management

**How to test the change?**
Built packages need to be tested with internal tooling

2024-05-24 08:02 UTC, BaptisteFoy approved these changes

2024-05-24 09:11 UTC, BaptisteFoy commented on .gitlab-ci.yml
> +    FLAVOR: datadog-apm-library-rb
```suggestion
    FLAVOR: datadog-apm-library-ruby
```

2024-05-24 09:11 UTC, BaptisteFoy commented on .gitlab-ci.yml
> +    IMG_DESTINATIONS: apm-library-rb-package:pipeline-${CI_PIPELINE_ID}
```suggestion
    IMG_SOURCES: registry.ddbuild.io/ci/remote-updates/datadog-apm-library-ruby:pipeline-${CI_PIPELINE_ID}-1
    IMG_DESTINATIONS: apm-library-ruby-package:pipeline-${CI_PIPELINE_ID}
```

2024-05-27 11:03 UTC, BaptisteFoy commented on .gitlab/build-oci-package.sh
> +  --package="datadog-apm-library-rb" \
```suggestion
  --package="datadog-apm-library-ruby" \
```

2024-05-27 11:03 UTC, BaptisteFoy commented on .gitlab/build-oci-package.sh
> +  --archive-path="datadog-apm-library-rb-$RUBY_PACKAGE_VERSION-$ARCH.tar" \
```suggestion
  --archive-path="datadog-apm-library-ruby-$RUBY_PACKAGE_VERSION-$ARCH.tar" \
```

2024-05-27 11:34 UTC, BaptisteFoy commented on .gitlab/build-oci-package.sh
> +cp -r ../tmp sources
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**❓ Question:** ‏Shouldn't it be this instead?
```suggestion
cp -r ../tmp/* sources
```

Else the content of the package looks like this: 
```
$ ls -lah
total 16K
drwxr-xr-x 3 root root 4.0K May 27 11:31 .
drwxr-xr-x 3 root root 4.0K May 27 11:31 ..
drwxr-xr-x 6 root root 4.0K May 27 11:31 tmp
-rw-r--r-- 1 root root   41 May 27 11:31 version
```

2024-05-27 13:06 UTC, BaptisteFoy reviewed
Also I tested it, looks like https://github.com/DataDog/dd-trace-rb/blob/b908262754eed55fbca8826d130c870760716f07/lib-injection/host_inject.rb#L9 prevents us from using the right path

2024-05-28 13:07 UTC, TonyCTHsu requested changes
Generally, it is fine. 

I submitted `Request changes` because we need to validate this artifact before merging.

2024-05-30 10:34 UTC, TonyCTHsu approved these changes
The test is passing! 👍

2024-05-30 11:45 UTC, merged