Add lib injection support for Ruby 3.3
DataDog/dd-trace-rb pull request #4001
Opened 2024-10-15 16:53 UTC by marcotc

Support for Ruby 3.3 is present in the gem, the only thing needed for injection is to change the installation script to allow it to run with that version of Ruby.

Because the Ruby API does not change in incompatible ways in between patch versions, we declare our compatibility with the API version "3.3.0", thus supporting all 3.3.x versions.

**How to test the change?**

Unsure? Have a question? Request a review!

2024-10-15 18:00 UTC, p-datadog approved these changes

2024-10-15 18:00 UTC, p-datadog commented on lib-injection/host_inject.rb
>            ruby_api_version = "#{major}.#{minor}.0"
What is the purpose of `.0` here? If only two components are used by the logic why not just have two components here?

2024-10-16 10:57 UTC, TonyCTHsu requested changes
What is blocking?

- Need a custom Ruby 3.3 image to build gems in a static way
- We are currently dealing with package size constraint, which is a prerequisite of this PR.

2024-10-18 19:01 UTC, marcotc commented
@TonyCTHsu
> Need a custom Ruby 3.3 image to build gems in a static way
Where are these images stored?

2024-10-23 08:05 UTC, ivoanjo commented
> Where are these images stored?

Afaik the dockerfiles are those in https://github.com/DataDog/dd-trace-rb/tree/master/.gitlab . I'm not sure how the rest of the pipeline is set up.

It may be worth documenting this somewhere? E.g. so it's clear how we can every year add new Ruby versions for the injection.

2024-11-21 13:13 UTC, TonyCTHsu commented
Obsolete by: https://github.com/DataDog/dd-trace-rb/pull/4137

2024-11-21 13:13 UTC, closed without merging