Add config support for "on_error" in Elasticsearch tracing
DataDog/dd-trace-rb pull request #4066
Opened 2024-11-05 10:55 UTC by bill-kolokithas

This mirrors the functionality that is already present in many other instrumenters.

Reasons for wanting this:

One might want to ignore some errors in some expected scenarios such as

`Elasticsearch::Transport::Transport::Errors::NotFound`
or
`Elasticsearch::Transport::Transport::Errors::Conflict`

**What does this PR do?**
Adds `on_error` configuration support for Elasticsearch tracing and forwards it to `Tracing.trace`

**Motivation:**
We have flows where `NotFound` exceptions are expected and we make sure to handle them in the application.
We don't want them to show up as errors in the dashboard though.

**How to test the change?**
Run provided tests with `bundle exec rake test:elasticsearch`

2024-11-05 18:59 UTC, rtrieu requested changes
Minor feedback on tense.

2024-11-05 18:59 UTC, rtrieu commented on docs/GettingStarted.md
> +| `on_error` | | `Proc` | Custom error handler invoked when a request raises an error. Provided `span` and `error` as arguments. Sets error on the span by default. Useful for ignoring transient error
```suggestion
| `on_error` | | `Proc` | Custom error handler invoked when a request raises an error. Provides `span` and `error` as arguments. Sets error on the span by default. Useful for ignoring transient errors. | `proc { \|span, error\| span.set_error(error) unless span.nil? }` |
```

2024-11-05 21:32 UTC, bill-kolokithas commented on docs/GettingStarted.md
> +| `on_error` | | `Proc` | Custom error handler invoked when a request raises an error. Provided `span` and `error` as arguments. Sets error on the span by default. Useful for ignoring transient error
Thanks! fixup: https://github.com/DataDog/dd-trace-rb/pull/4066/commits/1dc216f35ce8b70deeacf60acc67e0c5d4b74e2b

2024-11-06 14:41 UTC, rtrieu approved these changes

2024-11-25 22:55 UTC, marcotc approved these changes

2024-11-26 08:38 UTC, Strech approved these changes
Well done 👏🏼 

I've updated PR body and add **Change log entry** section

2024-11-26 14:24 UTC, merged